<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Chalk.Sample.Quickstart</RootNamespace>
    <AssemblyName>Chalk.Sample.Quickstart</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Chalk.Client/Chalk.Client.csproj" />
    <ProjectReference Include="../../src/Chalk.Sources.Poco/Chalk.Sources.Poco.csproj" />
  </ItemGroup>

</Project>
