package chalk.planner.plan.rules;

import java.util.Objects;
import java.util.function.Function;
import org.apache.calcite.plan.RelOptRule;
import org.apache.calcite.plan.RelRule;
import org.apache.calcite.rel.core.RelFactories;
import org.apache.calcite.tools.RelBuilderFactory;

/**
 * D134 — the one {@link RelRule.Config} every Chalk {@link RelRule} is built from.
 *
 * <p>Calcite 1.42 deprecates the static operand helpers on {@link RelOptRule} — {@code operand},
 * {@code operandJ}, {@code some}, {@code unordered}, {@code any}, {@code none} — in favour of
 * {@code RelRule<C extends RelRule.Config>} configured through {@link RelRule.OperandBuilder}.
 * Calcite's own configs are generated by the Immutables annotation processor, and {@code
 * RelRule.Config.EMPTY} no longer exists in 1.42; Chalk does not take the processor (it keeps
 * {@code org.immutables:value-annotations} as a {@code compileOnly} dependency, present only so
 * Calcite's own annotated interfaces read cleanly), so this hand-written immutable stands in for
 * one generated config per rule.
 *
 * <p>It carries what {@link RelRule}'s constructor asks a config for — the description, the operand
 * supplier and the {@link RelBuilderFactory} — plus the factory {@link #toRule()} applies. A rule
 * with parameters of its own (a {@code PushdownPolicy}, a {@code SourceConvention}) captures them in
 * that factory lambda and keeps them as fields, exactly as it did when it extended {@link
 * RelOptRule} directly.
 *
 * <p>Instances are immutable; every {@code with…} returns a copy.
 */
public final class ChalkRuleConfig implements RelRule.Config {
  private final String description;
  private final RelRule.OperandTransform operandSupplier;
  private final RelBuilderFactory relBuilderFactory;
  private final Function<ChalkRuleConfig, RelOptRule> ruleFactory;

  private ChalkRuleConfig(
      String description,
      RelRule.OperandTransform operandSupplier,
      RelBuilderFactory relBuilderFactory,
      Function<ChalkRuleConfig, RelOptRule> ruleFactory) {
    this.description = Objects.requireNonNull(description, "description");
    this.operandSupplier = Objects.requireNonNull(operandSupplier, "operandSupplier");
    this.relBuilderFactory = Objects.requireNonNull(relBuilderFactory, "relBuilderFactory");
    this.ruleFactory = Objects.requireNonNull(ruleFactory, "ruleFactory");
  }

  /**
   * A config with the default {@code LOGICAL_BUILDER}.
   *
   * @param description the rule description, which is what a rule set and a rule trace name
   * @param operands the operand tree, built through {@link RelRule.OperandBuilder}
   * @param ruleFactory what {@link #toRule()} applies to this config
   */
  public static ChalkRuleConfig of(
      String description,
      RelRule.OperandTransform operands,
      Function<ChalkRuleConfig, RelOptRule> ruleFactory) {
    return new ChalkRuleConfig(
        description, operands, RelFactories.LOGICAL_BUILDER, ruleFactory);
  }

  @Override
  public String description() {
    return description;
  }

  @Override
  public ChalkRuleConfig withDescription(String description) {
    return new ChalkRuleConfig(description, operandSupplier, relBuilderFactory, ruleFactory);
  }

  @Override
  public RelRule.OperandTransform operandSupplier() {
    return operandSupplier;
  }

  @Override
  public ChalkRuleConfig withOperandSupplier(RelRule.OperandTransform transform) {
    return new ChalkRuleConfig(description, transform, relBuilderFactory, ruleFactory);
  }

  @Override
  public RelBuilderFactory relBuilderFactory() {
    return relBuilderFactory;
  }

  @Override
  public ChalkRuleConfig withRelBuilderFactory(RelBuilderFactory factory) {
    return new ChalkRuleConfig(description, operandSupplier, factory, ruleFactory);
  }

  @Override
  public RelOptRule toRule() {
    return ruleFactory.apply(this);
  }
}
