#!/usr/bin/env python3
"""Write ChalkQL's planner-sidecar third-party notices from the bundled shadow jar.

    scripts/third-party-notices.py [repo-root] [jar]

Every Maven artefact inside chalk-planner.jar
(META-INF/maven/<group>/<artifact>/pom.properties) is listed with its version
and licence.

A group this script does not know is an error, so introducing a new bundled
dependency requires its licence to be classified before ChalkQL can be packed.

The generated notice belongs to the ChalkQL NuGet package because the planner
sidecar is now distributed as part of ChalkQL rather than as a separate
ChalkQL.Planner package.
"""

import glob
import os
import re
import sys
import zipfile


LICENCES = [  # longest prefix wins
    ('ch.qos.logback', 'EPL-1.0 OR LGPL-2.1'),
    ('com.fasterxml.jackson', 'Apache-2.0'),
    ('com.google.android', 'Apache-2.0'),
    ('com.google.api.grpc', 'Apache-2.0'),
    ('com.google.code.findbugs', 'BSD-3-Clause'),
    ('com.google.code.gson', 'Apache-2.0'),
    ('com.google.errorprone', 'Apache-2.0'),
    ('com.google.guava', 'Apache-2.0'),
    ('com.google.j2objc', 'Apache-2.0'),
    ('com.google.protobuf', 'BSD-3-Clause'),
    ('com.google.uzaygezen', 'Apache-2.0'),
    ('com.googlecode.json-simple', 'Apache-2.0'),
    ('com.jayway.jsonpath', 'Apache-2.0'),
    ('com.yahoo.datasketches', 'Apache-2.0'),
    ('commons-codec', 'Apache-2.0'),
    ('commons-io', 'Apache-2.0'),
    ('commons-logging', 'Apache-2.0'),
    ('io.grpc', 'Apache-2.0'),
    ('io.netty', 'Apache-2.0'),
    ('io.perfmark', 'Apache-2.0'),
    ('jakarta.transaction', 'EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0'),
    ('net.hydromatic', 'Apache-2.0'),
    ('net.minidev', 'Apache-2.0'),
    ('org.apache', 'Apache-2.0'),
    ('org.apiguardian', 'Apache-2.0'),
    ('org.checkerframework', 'MIT'),
    ('org.codehaus.janino', 'BSD-3-Clause'),
    ('org.codehaus.mojo', 'MIT'),
    ('org.jooq', 'Apache-2.0'),
    ('org.jspecify', 'Apache-2.0'),
    ('org.locationtech.jts', 'EPL-2.0 OR EDL-1.0'),
    ('org.locationtech.proj4j', 'Apache-2.0'),
    ('org.ow2.asm', 'BSD-3-Clause'),
    ('org.slf4j', 'MIT'),
    ('org.yaml', 'Apache-2.0'),
]


def licence(group):
    best = max(
        (prefix for prefix, _ in LICENCES
         if group == prefix or group.startswith(prefix + '.')),
        key=len,
        default=None,
    )
    if best is None:
        sys.exit(
            f"third-party-notices: no licence known for group {group}; "
            "add it to LICENCES"
        )
    return dict(LICENCES)[best]


root = os.path.abspath(
    sys.argv[1]
    if len(sys.argv) > 1
    else os.path.join(os.path.dirname(__file__), '..')
)

jars = sorted(glob.glob(
    os.path.join(
        root,
        'planner',
        'build',
        'libs',
        'chalk-planner-*-all.jar',
    )
))

jar = (
    sys.argv[2]
    if len(sys.argv) > 2
    else (
        jars[-1]
        if jars
        else sys.exit(
            "no planner jar: build one with "
            "'planner/gradlew -p planner shadowJar'"
        )
    )
)

rows = []

with zipfile.ZipFile(jar) as z:
    for name in z.namelist():
        match = re.fullmatch(
            r'META-INF/maven/([^/]+)/([^/]+)/pom\.properties',
            name,
        )
        if not match:
            continue

        props = dict(
            line.split('=', 1)
            for line in z.read(name).decode().splitlines()
            if '=' in line and not line.startswith('#')
        )

        rows.append((
            match.group(1),
            match.group(2),
            props.get('version', '?'),
        ))

rows.sort()

if not rows:
    sys.exit(
        f"third-party-notices: no Maven artefacts found in {jar}"
    )

width = max(len(f"{g}:{a}:{v}") for g, a, v in rows) + 2

out = [
    'ChalkQL planner sidecar — third-party notices',
    '',
    'The ChalkQL NuGet package includes chalk-planner.jar, a runnable JVM sidecar that bundles',
    'Apache Calcite and the libraries listed below, each used under its own licence. The upstream',
    'LICENSE and NOTICE files travel inside the jar under META-INF/ (META-INF/LICENSE,',
    'META-INF/NOTICE, META-INF/DEPENDENCIES and, for the shaded Netty and BoringSSL that gRPC',
    'carries, META-INF/license/). ChalkQL itself is Apache-2.0; see LICENSE and NOTICE at the root',
    'of the repository.',
    '',
    'This file is generated by scripts/third-party-notices.py from the exact shadow jar packaged',
    'with ChalkQL and is regenerated by scripts/pack.sh.',
    '',
]

for group, artifact, version in rows:
    coordinate = f'{group}:{artifact}:{version}'
    out.append(f"  {coordinate:<{width}}{licence(group)}")

out.append('')

target = os.path.join(
    root,
    'dotnet',
    'packaging',
    'ChalkQL.Package',
    'THIRD-PARTY-NOTICES.txt',
)

with open(target, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(out))

print(f"{len(rows)} artefacts -> {os.path.relpath(target, root)}")